version: '3.9'
services:
  client:
    restart: unless-stopped
    image: client:latest
    ports:
      - 8080:8080
      # - 8080:${APP_PORT}
      - 43045:43045
    volumes:
      - ./client:/usr/src/app
    links:
      - server
    command: npm start
    tty: true
    stdin_open: true

  server:
    restart: unless-stopped
    image: server:latest
    ports:
      - 8000:${API_PORT}
    volumes:
      - ./server:/user/src/app
    command: npm run start:docker
    tty: true
    stdin_open: true
    environment:
      - API_PORT=${API_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_HOST=${POSTGRES_HOST}

  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
